CREATE USER ng_user WITH PASSWORD 'francky';
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO ng_user;
GRANT SELECT, USAGE ON ALL SEQUENCES IN SCHEMA public TO ng_user;
--GRANT SELECT, USAGE ON SEQUENCES TO francky;