CREATE USER postgres WITH PASSWORD 'francky';
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO postgres;
GRANT SELECT, USAGE ON ALL SEQUENCES IN SCHEMA public TO postgres;
--GRANT SELECT, USAGE ON SEQUENCES TO francky;