version: '3'
services:

  ng-db:
    image: ng-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: francky
      POSTGRES_DB: ng-db
    build:
      context: postgresql
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "16432:5432"
    networks:
      - backend

  ng-api:
    build:
      context: api
    image: ng-api
    ports:
      - "8081:8081"
    environment:
      DB_URL: jdbc:postgresql://ng-db:5432/ng-db
      DB_USERNAME: ng_user
      DB_PASSWORD: francky
      MAIL_USERNAME: devtounga@gmail.com
      MAIL_PASSWORD: francky007
      MAIL_RECEIVER: ${MAIL_RECEIVER}
      SPRING_PROFILES_ACTIVE: dev
      OAUTH_JWK_URI: https://www.googleapis.com/oauth2/v3/certs
      OAUTH_USER_INFO_URI: https://openidconnect.googleapis.com/v1/userinfo
      OAUTH_JWK_CLIENT_ID: 497106959400-37o2m3pa1tvcig4hp2sqqtn6ma731hq0.apps.googleusercontent.com
    depends_on:
      - ng-db
    networks:
      - backend

  ng-app:
    build:
      context: app
    image: ng-app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    depends_on:
      - ng-api
    ports:
      - "80:80"
      - "443:443"
    volumes: 
     - ./data/certs:/etc/nginx/certs
    networks:
      - backend
      
volumes:
  postgres:

networks:
  backend:
    driver: "bridge"
