-- Init users table
INSERT INTO users (id_user, name, email, age) VALUES (1, 'Franck', 'ntounga@gmail.com', 30);

-- Init formation table
INSERT INTO formation (id, title, url_img, location, lesson_count, total_minutes) values (1, 'Mise en place serveur', '/assets/img/apache.png', 'https://toungafranck.com/mise-en-place-serveur/', 13, 163);
INSERT INTO formation (id, title, url_img, location, lesson_count, total_minutes) values (2,'Jenkins', '/assets/img/jenkins.png', 'https://toungafranck.com/jenkins-3/', 15, 170);
INSERT INTO formation (id, title, url_img, location, lesson_count, total_minutes) values (3,'Elasticsearch', '/assets/img/elasticsearch.png', 'https://toungafranck.com/elastic/', 22, 240);
INSERT INTO formation (id, title, url_img, location, lesson_count, total_minutes) values (4,'Docker', '/assets/img/docker-1.png', '', 0, 0);

-- Init lesson table
insert into lesson (id_lesson, title, source_url, duration, preview, id_formation) values (1, '1- Presentation de la formation', 'https://www.youtube.com/embed/9UYMwwXR8tQ', 7, 'Dans le cadre de la mise en place d’un environnement de développement, il est nécessaire de configurer un serveur Web. Il sera question ici de présenter les différents modules qui vous permettent d’y arriver.', 1);
insert into lesson (id_lesson, title, source_url, duration, preview, id_formation) values (2, '2- Installation Ubuntu', 'https://www.youtube.com/embed/x7ykUoFzClQ', 9, 'Afin de ne pas avoir à souscrire à un serveur dédié, on utilisera une machine virtuelle via VirtualBox. Cet outil nous permettra de faire tourner un OS embarqué (Linux) sur notre machine', 1);
insert into lesson (id_lesson, title, source_url, duration, preview, id_formation) values (3, '3- Les commandes Unix Part 1', 'https://www.youtube.com/embed/HV8v8ileO5w', 15, 'Découverte des commandes qui vous permettrons de naviguer aisément dans le terminal UNIX:cd, ls, mv, ln', 1);
insert into lesson (id_lesson, title, source_url, duration, preview, id_formation) values (4, '4- Les commandes Unix Part 2', 'https://www.youtube.com/embed/NuOY10c0M30', 19, '2ème partie sur les commandes UNIX qui vous permettrons de gérer les permissions attribuées à vos fichiers, les propriétaires associés et celle qui vous permettrons de mettre à jour et d’installer de nouveaux paquets sur UNIX: chmod, chown, apt-get', 1);
insert into lesson (id_lesson, title, source_url, duration, preview, id_formation) values (5, '5- Vim', 'https://youtube.com/embed/n3kqGo1OtXw', 6, 'Présentation du logiciel Vim. C’est un éditeur de fichier sous Unix. On verra les deux modes disponibles: La navigation et l’insertion. Ensuite une brève présentation de quelques raccourcis de base: :q, :wq!, dd, yy, p …etc', 1);
insert into lesson (id_lesson, title, source_url, duration, preview, id_formation) values (6, '6- SSH', 'https://www.youtube.com/embed/RpljfjbxWIs', 19, 'Le SSH (Secure shell) est à la fois un programme informatique et un protocole de communication. Il permet de sécuriser les échanges lorsqu’un client se connecte à une machine à distance. Il supporte 2 modes d’authentification: par nom d’utilisateur et mot de passe ou par couple clé publique - clé privée. Présentation et utilisation du logiciel Putty.', 1);
insert into lesson (id_lesson, title, source_url, duration, preview, id_formation) values (7, '7- Apache', 'https://www.youtube.com/embed/iXuAK3hYZcQ', 47, 'Installation et configuration du serveur Apache. Mise en place d’hôtes virtuels. Configuration des ports, Activation de modules apache. Edition de fichier .htaccess, configuration de fichier de log. Gestion des permissions apaches', 1);
insert into lesson (id_lesson, title, source_url, duration, preview, id_formation) values (8, '8- SSL', 'https://www.youtube.com/embed/iXuAK3hYZcQ', 20, 'Génération et installation d’un certificat auto-signé. Générations de la clé privée SSL. Génération du fichier csr ( certificate signing request ). Intégration du certificat et de la clé à Apache.', 1);
insert into lesson (id_lesson, title, source_url, duration, preview, id_formation) values (9, '9- Tomcat', 'https://www.youtube.com/embed/2pmqRSc5JFM', 22, 'Installation de Tomcat et intégration à notre Apache. Déploiement d’une application Java sur notre Tomcat. Configuration de la console admin. Mise en place de redirection et activation du mode proxy_http', 1);
insert into lesson (id_lesson, title, source_url, duration, preview, id_formation) values (10, '10- Mysql', 'https://www.youtube.com/embed/Hy4p-rcDuOk', 19, 'Installation et configuration d’une base de données Mysql. Création d’une base de données, d’un utilisateur et mise en place de privilèges. Configuration de notre bind address. Optimisation de notre base de donées via la journalisation de requêtes lentes.', 1);
insert into lesson (id_lesson, title, source_url, duration, preview, id_formation) values (11, '11- Iptables', 'https://www.youtube.com/embed/ZVK4d2Vv93k', 19, 'Configuration du firewall Iptables. Création d’un fichier de scripts sh pour persister les règles du parefeu. Fermeture de tous les ports. Ouvertures de ports spécifique(ssh,http..etc) et exécution du script en tant que service par défaut', 1);
insert into lesson (id_lesson, title, source_url, duration, preview, id_formation) values (12, '12- Ufw (Uncomplicated firewall)', 'https://www.youtube.com/embed/BxkQk3eF-pM', 16, 'Installation et configuration du firewall Ufw. Utilisation du mot clé allow/deny. Mise en place et suppression des régles de base au niveau du parefeu. Configuration du firewall à partir de la liste d’application connues par ufw. Misen en places de règles plus complexes spécifiant l’adresse IP.', 1);
insert into lesson (id_lesson, title, source_url, duration, preview, id_formation) values (13, '13- Postfix', 'https://www.youtube.com/embed/YTd3CbSigzw', 12, 'Installation et configuration de Postfix. Mise en place du nom de domain dans sa configuration d’administration lors de son installation. Configuration de notre inet_interfaces en loopback-only. On peut consolider la config grâce à un parefeu en bloquant les ports inutilisés', 1);
insert into lesson (id_lesson, title, source_url, duration, preview, id_formation) values (14, '14- Fail2ban', 'https://www.youtube.com/embed/sc4kWEGXz5k', 23, 'Installation et configuration de Faile2ban. Mise en place de la banactions. Configuration et test des filtres ssh et apache-noscripts grâce au module fail2ban-regex. Configuration du destinaire des emails d’alertes et de l’outil responsable de leur envoi (Sendermail ou Postfix). NB: Il faut s’assurer que fournisseur d’accès ne bloque pas les connexion sortante sur son port 25 (SMTP)', 1);
insert into lesson (id_lesson, title, source_url, duration, preview, id_formation) values (15, '15- Proftpd', 'https://www.youtube.com/embed/mufo0g4MDyE', 20, 'Installation et configuration d''un serveur Proftpd. C''est un serveur de transfert de fichiers. Creation d''utilisateurs Unix associés à notre serveur ftp. Configuration du pare feu pour permettre la transmission via le mode passif. Mise en place de l''outil quota afin de gerer l''espace mémoire allouée à chaque utilisateur.', 1);

-- Init tutoriel table
insert into tutoriel (id, title, url_img, location, type, disponible) values (1,'Nouveautés Java 8', '/assets/img/java-8.png', 'https://toungafranck.com/les-nouveautes-de-java-8-preview/', 'BOOK', true);
insert into tutoriel (id, title, url_img, location, type, disponible) values (2,'Protocole TLS/SSL', 'assets/img/ssl.png', 'https://toungafranck.com/le-protocole-tls-ssl/', 'GUIDE', true);
insert into tutoriel (id, title, url_img, location, type, disponible) values (3,'Elasticsearch', '/assets/img/elasticsearch.png', 'https://toungafranck.com/elasticsearch-3/', 'BOOK', true);
insert into tutoriel (id, title, url_img, location, type, disponible) values (4,'Authentification JWT', '/assets/img/jwt.png', 'https://toungafranck.com/authentification-jwt-json-web-token/', 'GUIDE', true);
insert into tutoriel (id, title, url_img, location, type, disponible) values (5,'Sring Data & Elastic', '/assets/img/spring-data-elastic.png', '', 'GUIDE', false);
insert into tutoriel (id, title, url_img, location, type, disponible) values (6,'Sring Boot & Kafka', 'assets/img/Kafka.png', '', 'GUIDE', false);
insert into tutoriel (id, title, url_img, location, type, disponible) values (7,'Sring & Reactor', 'assets/img/spring-reactor.jpeg', '', 'GUIDE', false);

-- Init article table
insert into article (id, title, url_img, preview, location, date_creation) values (1, 'Installation d’un cluster Elasticsearch en production', '/assets/img/elastic-blog-2.png', 'Elasticsearch est un serveur de recherche open source populaire utilisé pour la recherche distribuée en temps réel et l’analyse de données. Lorsqu’il est utilisé pour autre chose que le développement, Elasticsearch doit être déployé sur plusieurs serveurs en tant que cluster, pour des performances, une stabilité et une évolutivité optimales', 'https://toungafranck.com/2019/07/18/installation-dun-cluster-elasticsearch-en-production-ubuntu-14-04/', '2019-6-18');
insert into article (id, title, url_img, preview, location, date_creation) values (2, 'Dockeriser vos applications Spring boot', '/assets/img/docker-springboot.png', 'J’ai decouvert Docker récemment durant ma mission à Bruxelles au sein de l’acteur Buyway, leader sur le marché en solution de crédit. L’idée d’écrire une brève introduction sur le sujet m’est arrivée durant ma collaboration avec l’analyste Redouane. Dans cet article, vous apprendrez à créer une image Docker pour exécuter une application Spring Boot', 'https://toungafranck.com/2019/05/21/dockeriser-vos-applications-spring-boot/', '2019-5-21');
insert into article (id, title, url_img, preview, location, date_creation) values (3, 'Programmation reactive avec Spring 5', '/assets/img/reactive-springboot.png', 'Ces derniers temps, la programmation réactive a gagné en popularité auprès de la communauté des développeurs et des clients en raison de sa capacité à concevoir des applications de manière déclarative, et non impérative, ce qui a entraîné des applications plus réactives et résilientes.', 'https://toungafranck.com/2018/06/04/programmation-reactive-avec-spring-5/','2019-6-4');
insert into article (id, title, url_img, preview, location, date_creation) values (4, 'L’API Stripe', '/assets/img/stripe-springboot.png', 'L’air est au business sur internet. Qui dit business dit paiement. C’est à ce niveau que les choses se corsent pour les développeurs. De nombreuses plateformes existent sur le marché et choisir la bonne implémentation n’est pas souvent chose aisée du fait du manque de documentation', 'https://toungafranck.com/2018/05/22/lapi-stripe/', '2019-5-22');
insert into article (id, title, url_img, preview, location, date_creation) values (5, 'JWT – JSON WEB TOKEN', '/assets/img/JWT-1.png', 'Introduction L’utilisation d’API tièrces au sein d’applications est devenue monnaie courante. Ceci est dû au fait que les applications ne peuvent plus compter sur leurs propres données. Pour qu’un projet puisse voir son potentiel décuplé, il doit pouvoir avoir des applications tierces, s’interopérer avec ces dernières et avoir facilement accès à ses données', 'https://toungafranck.com/2018/03/19/jwt-json-web-token/', '2019-3-19');
insert into article (id, title, url_img, preview, location, date_creation) values (6, 'Introduction au data binding ANGULAR 1 VS ANGULAR 2', '/assets/img/data-binding.png', 'En prévision de la formation sur angular 5, prévue en fin avril 2018, dans la NG-ACADEMY, j’ai décidé de me pencher sur un des concepts de base d’angular: le data binding. Il existe plusieurs façons de lier des données dans Angular: interpolation, liaison unidirectionnelle (one way binding), liaison bidirectionnelle(two way binding) et liaison d’événement(event binding)', 'https://toungafranck.com/2018/03/06/2076-data-binding-in-angular/', '2019-3-6');

